on: push
name: Run tests
jobs:
  tests:
    name: Tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.15'
      - run:
          - go version
          - go get
          - go test ./...