name: Go tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.15"

      - name: Go Version
        run: go version

      - name: Get Deps
        run: go get

      - name: Test
        run: go test -v ./... --covermode=atomic -coverprofile coverage.out
